name: .NET Core W3CTestSuite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Test W3CTestSuite
      run: ./W3CTestSuite.sh
    - name: Artifacts W3CTestSuite
      uses: actions/upload-artifact@master
      with:
        name: W3CTestSuite
        path: ./temp/W3CTestSuite
